name: 🚀 Deploy SmartLead to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy even if no changes'
        required: false
        default: 'false'

jobs:
  deploy:
    name: 🌐 Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🚀 Deploy to Production Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Cores para output
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          YELLOW='\033[1;33m'
          BLUE='\033[0;34m'
          NC='\033[0m'
          
          echo -e "${GREEN}🚀 Iniciando deploy automático do SmartLead...${NC}"
          
          # Instalar dependências se necessário
          if ! command -v docker-compose &> /dev/null; then
            echo -e "${YELLOW}📦 Instalando Docker Compose...${NC}"
            curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
          fi
          
          if ! command -v docker &> /dev/null; then
            echo -e "${YELLOW}📦 Instalando Docker...${NC}"
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
          fi
          
          # Navegar para diretório ou criar
          cd /opt || mkdir -p /opt && cd /opt
          
          # Se não existe o diretório, fazer clone
          if [ ! -d "smartlead" ]; then
            echo -e "${YELLOW}📥 Clonando repositório...${NC}"
            git clone https://github.com/jeanasilva/test_smartlead.git smartlead
          fi
          
          cd smartlead
          
          # Atualizar código
          echo -e "${YELLOW}🔄 Atualizando código...${NC}"
          git fetch origin
          git reset --hard origin/main
          git clean -fd
          
          # Parar containers antigos
          echo -e "${YELLOW}🛑 Parando containers antigos...${NC}"
          docker-compose -f docker-compose.prod.yml down 2>/dev/null || true
          
          # Criar .env.prod com os secrets
          echo -e "${YELLOW}📝 Criando .env.prod...${NC}"
          cat > .env.prod << 'EOF'
          APP_NAME="SmartLead API"
          APP_ENV=production
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=false
          APP_URL=https://smartlead.jeansilva.dev.br
          
          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=error
          
          DB_CONNECTION=mysql
          DB_HOST=db
          DB_PORT=3306
          DB_DATABASE=smartlead_db
          DB_USERNAME=smartlead
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          
          REDIS_HOST=redis
          REDIS_PASSWORD=null
          REDIS_PORT=6379
          
          MAIL_MAILER=smtp
          MAIL_HOST=smtp.zoho.com
          MAIL_PORT=587
          MAIL_USERNAME=offboard@offboard.com.br
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_ENCRYPTION=tls
          MAIL_FROM_ADDRESS=offboard@offboard.com.br
          MAIL_FROM_NAME="SmartLead"
          
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          
          VUE_APP_API_BASE_URL=https://smartlead.jeansilva.dev.br/api
          
          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false
          
          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_APP_CLUSTER=mt1
          
          MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
          MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
          EOF
          
          # Verificar arquivo criado
          echo -e "${BLUE}✅ Arquivo .env.prod criado${NC}"
          ls -la .env.prod
          
          # Iniciar containers de produção
          echo -e "${YELLOW}🐳 Iniciando containers de produção...${NC}"
          docker-compose -f docker-compose.prod.yml up -d --build
          
          # Aguardar containers ficarem prontos
          echo -e "${YELLOW}⏳ Aguardando containers ficarem prontos...${NC}"
          sleep 60
          
          # Verificar status dos containers
          echo -e "${BLUE}📊 Status dos containers:${NC}"
          docker-compose -f docker-compose.prod.yml ps
          
          # Configurar aplicação Laravel se container estiver rodando
          if docker-compose -f docker-compose.prod.yml ps | grep -q "Up"; then
            echo -e "${YELLOW}📦 Configurando aplicação Laravel...${NC}"
            
            # Instalar dependências
            docker-compose -f docker-compose.prod.yml exec -T app composer install --no-dev --optimize-autoloader || true
            
            # Gerar chaves
            docker-compose -f docker-compose.prod.yml exec -T app php artisan key:generate --force || true
            docker-compose -f docker-compose.prod.yml exec -T app php artisan jwt:secret --force || true
            
            # Configurar banco
            docker-compose -f docker-compose.prod.yml exec -T app php artisan migrate --force || true
            docker-compose -f docker-compose.prod.yml exec -T app php artisan db:seed --force || true
            
            # Gerar documentação
            docker-compose -f docker-compose.prod.yml exec -T app php artisan l5-swagger:generate || true
            
            echo -e "${GREEN}✅ Aplicação Laravel configurada${NC}"
          else
            echo -e "${RED}❌ Containers não estão rodando corretamente${NC}"
            docker-compose -f docker-compose.prod.yml logs
          fi
          
          # Configurar nginx básico se necessário
          if [ ! -f /etc/nginx/sites-available/smartlead ]; then
            echo -e "${YELLOW}🌐 Configurando Nginx...${NC}"
            cat > /etc/nginx/sites-available/smartlead << 'NGINX_EOF'
          server {
              listen 80;
              server_name smartlead.jeansilva.dev.br;
              
              location / {
                  proxy_pass http://127.0.0.1:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
          NGINX_EOF
            
            ln -sf /etc/nginx/sites-available/smartlead /etc/nginx/sites-enabled/
            nginx -t && systemctl reload nginx || echo "Nginx não configurado"
          fi
          
          echo -e "${GREEN}✅ Deploy concluído!${NC}"
          echo -e "${BLUE}🌐 Teste: http://${{ secrets.SERVER_HOST }}:8080${NC}"
          
          # Teste final
          sleep 15
          curl -f http://localhost:8080 || echo "⚠️ Aplicação pode estar iniciando"
        
    - name: 🔍 Verify Deployment
      run: |
        echo "### 🚀 Deploy Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Status**: Deployment completed" >> $GITHUB_STEP_SUMMARY
        echo "🌐 **URL**: http://${{ secrets.SERVER_HOST }}:8080" >> $GITHUB_STEP_SUMMARY
        echo "🕐 **Time**: $(date)" >> $GITHUB_STEP_SUMMARY
